### ISSUE TITLE
Vowel-detector insufficient for "y"

### ISSUE THREAD

**Issue by ksen0** [dbarella/i-am-a#1]
On the the "y" adjectives requires an "a" (yammering) and another requires an "an" article (yttrium-based). Current implementation erroneously assigns an "a" to both of them! Suggested fix is to add an additional check for whether first letter is "y," and then if the following letter is in the vowels array, use "a," and otherwise, use "an." To achieve this, you would make the following logic amendment on https://github.com/dbarella/i-am-a/blob/master/i_am.py#L74 `if adjective.startswith(VOWELS) or ( /* adjective is at least 2 chars long */ and /* first letter is a 'y' */ and /* second letter is in vowels */):`

**Comment by dbarella** [comment]
Thanks @erose for fixing this. Hi @ksen0 !!!
